apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/podinfo
  - netshoot.yaml
patches:
  - path: podinfo-values.yaml
    target:
      kind: HelmRelease
      namespace: podinfo
configMapGenerator:
  - name: netshoot-values
    namespace: netshoot
    files:
      - values.yaml=netshoot-values.yaml
configurations:
  - kustomizeconfig.yaml
