apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/podinfo
  - nginx-test.yaml
patches:
  - path: podinfo-values.yaml
    target:
      kind: HelmRelease
      namespace: podinfo
