apiVersion: v1
kind: Namespace
metadata:
  name: netshoot
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netshoot
  namespace: netshoot
spec:
  releaseName: netshoot
  interval: 30m
  chart:
    spec:
      chart: helm/netshoot
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: netshoot-values
