apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-test
  namespace: nginx-test
spec:
  interval: 30m
  chart:
    spec:
      chart: ./helm/nginx
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 12h
  values:
    replicaCount: 2
